Stop redis/session complaining about LazyString
We were getting errors of the type:

TypeError: Encoding objects of type LazyString is unsupported

I believe this is because the login_manager.login_message was wrapped
with lazy_gettext()

It appears that flask_login instead should use a localize_callback
function, so that is set up instead.